  AWSTemplateFormatVersion: 2010-09-09

  Description: Continuous deployment infrastructure for IDP CDK Stack

  Parameters:
    RepoURL:
      Type: String
      Description: The Github Repository to be cloned into SageMaker Domain
      Default: 'https://github.com/aws-samples/aws-ai-intelligent-document-processing'

  Resources:
    LambdaExecutionRole:
      Type: "AWS::IAM::Role"
      Properties:
        Description: 'Lambda Role for Cloudformation'
        Policies:
          - PolicyName: cb-access
            PolicyDocument:
              Version: 2012-10-17
              Statement:
                - Effect: "Allow"
                  Action:
                    - codebuild:StartBuild
                  Resource: 
                    Fn::Join: 
                    - ""
                    - - 'arn:aws:codebuild:'
                      - !Ref AWS::Region
                      - ':'
                      - !Ref AWS::AccountId
                      - ':project/*'
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action:
                - "sts:AssumeRole"
        Path: /
        ManagedPolicyArns:
          - 'arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess'
          - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

    CodeBuildRole:
      Type: "AWS::IAM::Role"
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Service:
                  - "codebuild.amazonaws.com"
              Action:
                - "sts:AssumeRole"
        Policies:
          - PolicyName: "CodeBuildPolicy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - "sts:AssumeRole"
                  Resource:
                    - "arn:aws:iam::*:role/cdk-*"
                - Effect: "Allow"
                  Action:
                    - "logs:CreateLogGroup"
                    - "logs:CreateLogStream"
                    - "logs:PutLogEvents"
                  Resource:
                    Fn::Join: 
                    - ""
                    - - 'arn:aws:logs:'
                      - !Ref AWS::Region
                      - ':'
                      - !Ref AWS::AccountId
                      - ':log-group:/aws/codebuild/*'
                - Effect: "Allow"
                  Action:
                    - "s3:PutObject"
                    - "s3:GetObject"
                    - "s3:GetObjectVersion"
                    - "s3:GetBucketAcl"
                    - "s3:GetBucketLocation"
                  Resource:
                    - "*"
                - Effect: "Allow"
                  Action:
                    - "cloudformation:CreateChangeSet"
                    - "cloudformation:DeleteStack"
                    - "cloudformation:DescribeChangeSet"
                    - "cloudformation:DescribeStackEvents"
                    - "cloudformation:DescribeStacks"
                    - "cloudformation:ExecuteChangeSet"
                    - "cloudformation:GetTemplate"
                  Resource:
                    - "arn:aws:cloudformation:*:*:stack/CDKToolkit/*"
                - Effect: "Allow"
                  Action:
                    - "codebuild:CreateReportGroup"
                    - "codebuild:CreateReport"
                    - "codebuild:UpdateReport"
                    - "codebuild:BatchPutTestCases"
                    - "codebuild:BatchPutCodeCoverages"
                  Resource:
                    Fn::Join: 
                    - ""
                    - - 'arn:aws:codebuild:'
                      - !Ref AWS::Region
                      - ':'
                      - !Ref AWS::AccountId
                      - ':report-group/cb-report-group-1'
    CodeBuildProject:
      Type: AWS::CodeBuild::Project
      Properties:
        Name: IDPCodeBuild
        ServiceRole: !GetAtt CodeBuildRole.Arn
        Environment:
          Type: LINUX_CONTAINER
          ComputeType: BUILD_GENERAL1_SMALL
          Image: aws/codebuild/standard:5.0
          EnvironmentVariables:
            - Name: REPO_URL
              Type: PLAINTEXT
              Value: !Ref RepoURL
        Artifacts:
          Type: NO_ARTIFACTS        
        Source:
          Type: NO_SOURCE
          BuildSpec: |
            version: 0.2
            phases:
              install:
                commands:
                  - npm install -g aws-cdk
              pre_build:
                commands:
                  - git clone $REPO_URL
                  - cd idp-genai-aim-306
                  - pip install -r requirements.txt
                  - cdk bootstrap
              build:
                commands:
                  - cdk deploy SimpleAsyncWorkflow --outputs-file simple_async_workflow.json --require-approval never
              post_build:
                commands:
                  - cat simple_async_workflow.json
    
    BuildCodeBuildLambda:
      Type: AWS::Lambda::Function
      Properties:
        FunctionName: BuildCodeBuildLambda
        Code:
          ZipFile: |          
            import boto3            
            import cfnresponse
            cb = boto3.client('codebuild')
            def lambda_handler(event, context):   
                if 'RequestType' in event and event['RequestType'] == 'Create':             
                    try:
                        resp = cb.start_build(projectName="IDPCodeBuild")
                        cfnresponse.send(event, context, cfnresponse.SUCCESS, {'Message': "CodeBuild build started"},'')
                    except Exception as e:
                        cfnresponse.send(event, context, cfnresponse.FAILED, {'Message': "Unable to start CodeBuild build"}, '')
                elif 'RequestType' in event and event['RequestType'] == 'Delete':
                    cfnresponse.send(event, context, cfnresponse.SUCCESS, {'Message': "Custom resource deleted"},'')
        Description: Starts the IDP CDK flow build
        Handler: index.lambda_handler
        MemorySize: 128
        Role: !GetAtt LambdaExecutionRole.Arn
        Runtime: python3.9
        Timeout: 5
    BuildCodeBuild:
      Type: Custom::ResourceForStartingCodeBuild
      Properties:
        ServiceToken: !GetAtt BuildCodeBuildLambda.Arn